"""Reviewed staff journeys. Staging content proposals, never automatic page publication."""
from html import escape
# IDs and titles observed in the authenticated CRH page tree, 23 September 2026.
ROUTES=[
('381890661',"What's New",'updates.html','Support'),('381890664','Archive','archive.html','Support'),
('381891652','How To Work With Us','working-with-us.html','Creative help'),('381891657','FAQ','faq.html','Support'),('381891673','Self-Service Guides','self-service.html','Guidance'),('381891678','Formatting a Presentation','formatting-slides.html','Presentations'),('381891681','Making Your Own Poster','making-a-poster.html','Guidance'),('381891685','Preparing Files for Print','print-preparation.html','Guidance'),('381891661','Submitting a Request','request.html','Creative help'),('381891666','Turnaround Times','timing.html','Creative help'),('381891669','What We Can Help With','creative-services.html','Creative help'),
('381891606','Brand Guidelines','brand.html','Brand'),('381891610','Brand in Practice','brand-in-practice.html','Brand'),('381891614','Co-Branding CSIRO','co-branding-csiro.html','Brand'),('381891619','Co-Branding SARAO','co-branding-sarao.html','Brand'),('381891623','Colour Palette and Typography','colours-and-type.html','Brand'),('381891626','Logo Usage and Downloads','logo-guidance.html','Brand'),('381891631','SKAO Brand Book','brand-book.html','Brand'),
('381891696','Templates & Assets','resources.html','Resources'),('381891700','Document Templates','documents.html','Resources'),('381891703','Email Signatures','email-signatures.html','Documents'),('381891706','Letterheads','letterheads.html','Documents'),('381891709','Memo Templates','memos.html','Documents'),('381891712','Report Template','reports.html','Documents'),('381891715','Logos & Icons','logos.html','Brand'),
('381891718','Photography Media','media.html','Media'),('381891721','Accessing Canto','canto-guide.html','Media'),('381891724','Approved Hero Images','hero-images.html','Media'),('381891751','Event Photography','event-photos.html','Media'),('381891756','Image Usage Guidelines','image-usage.html','Media'),('381891776','Telescope Imagery','telescope-images.html','Media'),('381891782','Print Materials','print.html','Creative help'),('381891788','Business Cards','business-cards.html','Creative help'),
('381891794','Slide Decks & Presentations','presentations.html','Presentations'),('381891798','About SKAO Master Deck','master-deck.html','Presentations'),('381891805','Construction Progress Updates','construction-slides.html','Presentations'),('381891810','How To Submit Your Deck','contribute.html','Sharing'),('381891817','Poster Templates','poster-templates.html','Resources'),('381891821','Science Case Presentations','science-slides.html','Presentations'),('381891829','SKA-Low Overview','low-slides.html','Presentations'),('381891832','SKA-Mid Overview','mid-slides.html','Presentations'),('381891838','Specialised Decks','specialised-slides.html','Presentations'),('381891843','Standard SKAO Template','standard-template.html','Presentations'),('381891851','Widescreen Template','widescreen-template.html','Presentations'),
('381891854','Video & Animation','video.html','Media'),('381891857','B-Roll Library','b-roll.html','Media'),('381891860','Event Recordings','recordings.html','Media'),('381891863','Explainer Animations','animations.html','Media'),('381891866','Requesting New Video Content','video-request.html','Creative help'),
('381891637','Events Support','events.html','Events'),('381891643','Event Planning Checklist','event-checklist.html','Events'),('381891640','Health and Safety','event-safety.html','Events'),('381891646','Merchandise and Giveaways','merchandise.html','Events'),('381891649','Stand Design and Materials','stands.html','Events'),
('381891870','Tools & Resources','help.html','Support'),('381891873','Accessibility Guidelines','accessibility.html','Guidance'),('381891876','Adobe Firefly','firefly.html','Guidance'),('381891879','Canto DAM Access','canto-access.html','Media'),('381891882','Font Downloads','fonts.html','Brand'),('381891885','Print Supplier Contacts','print-suppliers.html','Creative help')]
META={filename:{'id':id,'source_title':title,'group':group} for id,title,filename,group in ROUTES}
def link(url,label,cls=''):return f'<a href="{escape(url,quote=True)}" class="{cls}">{label}</a>'
def intro(text,url='',label='',tag=''):
 return '<div class="task-intro"><div>'+('<span class="eyebrow">'+tag+'</span>' if tag else '')+'<p>'+text+'</p></div>'+(link(url,label,'button') if url else '')+'</div>'
def cards(items):
 return '<div class="choice-grid">'+''.join('<a class="choice-card" href="'+url+'"><span class="choice-index" aria-hidden="true">'+str(i+1).zfill(2)+'</span><h2>'+title+'</h2><p>'+desc+'</p><span class="choice-go">'+cta+' <span aria-hidden="true">→</span></span></a>' for i,(title,desc,url,cta) in enumerate(items))+'</div>'
def block(title,items,ordered=False):
 tag='ol' if ordered else 'ul'
 return '<section class="reading-section"><h2>'+title+'</h2><'+tag+'>'+''.join('<li>'+s+'</li>' for s in items)+'</'+tag+'></section>'
def detail(title,body):return '<details class="guidance-detail"><summary>'+title+'</summary><div>'+body+'</div></details>'
def nextstep(title,text,url,label):return '<aside class="next-step"><div><h2>'+title+'</h2><p>'+text+'</p></div>'+link(url,label,'text-link')+'</aside>'
def missing(label,jira):return '<aside class="availability-note"><span class="availability-label">File not available on this page</span><h2>'+label+'</h2><p>The source page currently has no usable download link. Ask for the available file before planning around it.</p>'+link(jira,'Ask for this resource ↗','button secondary')+'</aside>'
def revise(pages,jira,canto):
 def put(name,title,body):pages[name]=(title,body)
 put('resources.html','Templates and assets',intro('Choose a starting point. Open its source page to see the file, guidance or availability information.',tag='Find and reuse')+cards([
 ('Presentation slides','Templates and decks for talks and briefings.','presentations.html','Find slides'),('Document templates','Reports, letters, memos and email signatures.','documents.html','Find a template'),('Logos and branding','Artwork, colours and practical identity guidance.','brand.html','Get the brand details'),('Photos and video','Find media and check credit and usage details in Canto.','media.html','Find media')])+nextstep('Missing a resource?','Send the page link and describe what you need.','request.html','Ask for help'))
 presentation_items=[('Start a new presentation','Use your own content with the standard layout.','standard-template.html','Check template availability'),('Introduce SKAO','Find a general overview to adapt for your audience.','master-deck.html','Check the master deck'),('Explain the science','Find source material for a science-focused talk.','science-slides.html','Explore science slides')]
 put('presentations.html','Prepare a presentation',intro('Choose the material that fits your audience, then check its source before reuse.',tag='Slides and talks')+cards(presentation_items)+
 '<aside class="source-check"><span class="eyebrow">Before downloading</span><h2>Check the release, not just the page date</h2><p>Look for a real file, its version, content owner and review date. Some source pages are still awaiting files; their availability is shown when you open them.</p></aside>'+
 detail('More presentation resources',cards([('Telescope overviews','SKA-Low and SKA-Mid source material.','low-slides.html','Start with SKA-Low'),('Construction updates','Dated progress slides and milestones.','construction-slides.html','Check updates'),('Specialised decks','Topic-specific material.','specialised-slides.html','Explore topics')])+link('mid-slides.html','SKA-Mid overview')+' · '+link('widescreen-template.html','Widescreen template'))+
 detail('Before you present',block('Four useful checks',['Keep credits, source information and speaker notes with reused slides.','Check facts against the source review date and ask the content or science owner about changes in meaning.','Check contrast, reading order and alternative text; caption video.','Check the presentation on the actual display or delivery format.'],True))+
 '<div class="reuse-decision"><h2>Reuse, adapt or ask?</h2><p>Use released material within its usage notes. Ask the content owner about changed claims; ask Creative Production about substantial design work.</p>'+link('request.html','Request creative help')+' · '+link('contribute.html','Share a presentation')+'</div>')
 # Keep the existing, tested six-field composer. Make it optional and remove repeated process prose.
 req=pages['request.html'][1];start=req.index('<form id="briefForm"');end=req.index('</form>',start)+7;form=req[start:end];ds=req.index('<section id="draftPanel"');de=req.index('</section>',ds)+10;draft=req[ds:de]
 put('request.html','Request creative help',intro('Already have a brief? Send it through the creative helpdesk with your files or source links.',jira,'Open creative helpdesk ↗','New work or a review')+
 '<div class="process-strip"><span><b>1</b> Describe the need</span><span><b>2</b> Submit in Jira</span><span><b>3</b> Agree scope and timing</span></div>'+
 '<details class="brief-builder"><summary>Need help writing the brief?</summary><div class="builder-content"><p>Use this optional helper, then copy the result into Jira. It does not submit a request.</p><p class="form-note">Fields marked * are required. Your draft is not saved and is lost if you leave or reload.</p>'+form+draft+'</div></details>'+
 '<noscript><p>Use the creative helpdesk directly. The optional brief helper needs JavaScript.</p></noscript>'+
 detail('What makes a useful brief?',block('Include these essentials',['Purpose, audience and the real use date.','Outputs, formats and what is outside the scope.','Draft content, source material and any missing inputs.','Content owner, final reviewer, budget and supplier constraints.']))+
 nextstep('A request is the start of a conversation','The team confirms capacity, scope and delivery timing after review.','timing.html','How timing is agreed')+
 '<p class="quiet-note">Planning an event? '+link('events.html','Brief the creative materials')+'. Event logistics stay with the events team.</p>')
 put('contribute.html','Share material',intro('Choose what you are sharing. Submission starts a review; it does not publish or approve a file.',tag='Make good work reusable')+
 '<div class="sharing-paths"><section><span class="route-label">01 / Presentations</span><h2>Send a deck for review</h2><p>Attach the editable deck or a suitable source link.</p>'+block('Include',['Title, intended audience and event or use date.','Content owner, source information and reuse restrictions.'])+link(jira,'Send a presentation ↗','button')+'</section><section><span class="route-label">02 / Photos and video</span><h2>Use your Canto upload route</h2><p>Include a useful title, creator, location and rights information. Use the authorised upload link supplied for your material.</p>'+link(jira,'Ask for the upload route ↗','button secondary')+'<p class="quiet-note">The '+link(canto,'Canto library ↗')+' is for browsing, not uploading.</p></section></div>'+
 nextstep('A correction, rather than a file?','Send the page URL, the change needed and its source.',jira,'Report a correction ↗')+
 detail('What happens after sharing?', '<p>The responsible owner checks the material before release. Presentation releases belong in the Hub; media remains in Canto. Keep working files at their source so a new attachment does not become a competing version.</p>'))
 brand_essentials='<div class="brand-specimens"><div class="colour-spec navy"><strong>Blueshift Navy</strong><div class="copy-row"><button type="button" class="copy-value" data-copy="#070068" aria-label="Copy Blueshift Navy hex #070068"><code>#070068</code><span>Copy</span></button><button type="button" class="copy-value" data-copy="7, 0, 104" aria-label="Copy Blueshift Navy RGB 7, 0, 104"><code>RGB 7, 0, 104</code><span>Copy</span></button></div></div><div class="colour-spec magenta"><strong>Redshift Magenta</strong><div class="copy-row"><button type="button" class="copy-value" data-copy="#E70068" aria-label="Copy Redshift Magenta hex #E70068"><code>#E70068</code><span>Copy</span></button><button type="button" class="copy-value" data-copy="231, 0, 104" aria-label="Copy Redshift Magenta RGB 231, 0, 104"><code>RGB 231, 0, 104</code><span>Copy</span></button></div></div><div class="type-spec"><span class="type-sample" aria-hidden="true">Aa</span><strong>Noto Sans</strong><small>Fallback: Verdana</small></div></div>'
 put('brand.html','Brand guidance',intro('Start from the official artwork and the Brand Book. Use these essentials as a quick reference.',tag='A consistent SKAO identity')+brand_essentials+cards([('Logo artwork','Find the supplied files and choose a suitable version.','logos.html','Find logo files'),('Colours and type','Digital colour values and practical typography guidance.','colours-and-type.html','Check the essentials'),('Brand Book','The source for detailed rules and applications.','brand-book.html','Open the source page')])+detail('Working with partner brands','<p>Use the current guidance for the specific partner and application. Do not assemble a new logo lock-up from memory.</p>'+link('co-branding-csiro.html','CSIRO co-branding')+' · '+link('co-branding-sarao.html','SARAO co-branding'))+nextstep('Need a second pair of eyes?','Include the draft, intended use and partner requirements.',jira,'Ask about the brand ↗'))
 put('events.html','Plan event materials',intro('Start with the audience, purpose and use date. Reuse existing material before commissioning something new.','request.html','Brief the creative work','Creative support for events')+
 '<div class="responsibility-split"><section><h2>Creative materials</h2><p>Presentation design, stand graphics, print, signage or video within an agreed brief.</p></section><section><h2>Event organisation</h2><p>Registration, attendance, travel, staffing and logistics remain with the events team.</p></section></div>'+
 cards([('Prepare the package','Gather specifications, content and review dates.','event-checklist.html','Use the checklist'),('Stand graphics','Brief an existing kit or a new visual layout.','stands.html','Plan the stand'),('Print or merchandise','Confirm purpose, quantity and supplier requirements.','print.html','Plan print materials')])+
 detail('Before committing to production',block('Confirm with the responsible teams',['Venue and supplier specifications, dimensions and delivery requirements.','Content owner, proof reviewer and budget approval.','Supplier lead time and the final artwork deadline.','Applicable safety requirements with the event organiser and HSSE.'])+link('event-safety.html','Find the HSSE route')+' · '+link('merchandise.html','Merchandise guidance')))
 put('help.html','Help with the Hub',intro('Find the right service or recover from a missing file or access problem.',tag='Support and useful tools')+cards([('Find photos or video','Search and download from the staff media library.','canto-access.html','Get to Canto'),('Request creative work','Brief new work or ask for a review.','request.html','Open the request guide'),('A missing or broken resource','Send the exact page link and what happened.',jira,'Report a problem ↗')])+
 detail('Where should I look for presentations?','<p>Start with '+link('presentations.html','presentation resources')+'. Released decks belong in the Hub. A page description is not a file download.</p>')+
 detail('Why can I browse but not upload?','<p>Browsing, downloading and contributing can have different permissions. Ask for the '+link('contribute.html','appropriate contribution route')+' rather than treating a library link as an upload form.</p>')+
 detail('Is my request booked once submitted?','<p>No. The team confirms scope, capacity and delivery timing after review. '+link('timing.html','Read how timing is agreed')+'.</p>')+
 '<section class="reading-section"><h2>Practical guides</h2><div class="resource-links">'+link('accessibility.html','Accessibility checks')+link('fonts.html','Fonts')+link('print-preparation.html','Preparing print files')+link('events.html','Event materials')+link('firefly.html','AI image tools')+'</div></section>')
 # Documents and presentation source pages: no download is invented.
 put('documents.html','Document templates',intro('Choose the document you need. Each source page shows whether a file is available.',tag='Start from a template')+cards([('Letterhead','Formal correspondence.','letterheads.html','Check the letterhead'),('Report','Longer documents and structured reports.','reports.html','Check the report template'),('Memo','Short internal documents.','memos.html','Check the memo template'),('Email signature','Consistent contact details.','email-signatures.html','Check signature files')])+nextstep('Need another format?','Describe the document, audience and intended use.','request.html','Ask for a template'))
 resource_data=[
 ('standard-template.html','Standard SKAO template','A starting layout for a presentation using your own content.','presentations.html'),('widescreen-template.html','Widescreen template','A 16:9 starting layout for suitable screens and webinars.','presentations.html'),('master-deck.html','About SKAO master deck','An overview for institutional introductions and general briefings.','presentations.html'),('science-slides.html','Science case presentations','Source material for science-focused talks and academic audiences.','presentations.html'),('construction-slides.html','Construction progress slides','Dated source material for progress updates and milestone briefings.','presentations.html'),('low-slides.html','SKA-Low overview','Source material about the SKA-Low telescope.','presentations.html'),('mid-slides.html','SKA-Mid overview','Source material about the SKA-Mid telescope.','presentations.html'),('specialised-slides.html','Specialised decks','Topic-specific decks for particular audiences.','presentations.html'),('poster-templates.html','Poster templates','Starting layouts for conference and research posters. Confirm size and orientation with the organiser.','resources.html'),('letterheads.html','Letterheads','A starting point for formal SKAO correspondence.','documents.html'),('reports.html','Report template','A starting point for structured reports.','documents.html'),('memos.html','Memo templates','A starting point for concise internal memos.','documents.html'),('email-signatures.html','Email signatures','Signature files and setup guidance for your email application.','documents.html')]
 for name,title,desc,parent in resource_data:
  put(name,title,intro(desc,tag='Resource source')+missing('Ask for the available '+('file' if name!='science-slides.html' else 'slides'),jira)+block('When you receive the file',['Check its version, content owner and intended use.','Save your working copy separately and retain credits and sources.','Check that facts and figures are current for your audience.'] if parent=='presentations.html' else ['Check that it is the appropriate released template for your use.','Create a separate working copy and use the supplied styles.','Review the finished document before sharing.'])+nextstep('Choose a different starting point','Return to the '+('presentation resources' if parent=='presentations.html' else 'document templates' if parent=='documents.html' else 'resource collection')+'.',parent,'Back to '+('presentations' if parent=='presentations.html' else 'document templates' if parent=='documents.html' else 'the collection')))
 put('logos.html','Logos and icons',intro('Use supplied artwork unchanged. Choose the variant for your background and output.',tag='Official artwork')+missing('Logo pack link needs completing',jira)+block('Choose the right file',['Use vector artwork where the output or supplier requires it.','Use the supplied light or dark background variant; do not recolour the logo yourself.','Keep the original proportions and follow the Brand Book’s clear-space guidance.'])+nextstep('Need usage guidance?','Check the identity rules before placing the artwork.','logo-guidance.html','Read logo guidance'))
 put('brand-book.html','SKAO Brand Book',intro('The Brand Book is the detailed source for visual identity rules.',tag='Source reference')+missing('Brand Book download needs completing',jira)+'<p class="quiet-note">The quick reference in this review build uses the retained SKAO Brand Book v2, March 2022. The source page’s older version label needs reconciliation before a downloadable release is published.</p>'+nextstep('Need the essentials now?','View the sourced digital colours and typeface.','colours-and-type.html','Colours and typography'))
 put('colours-and-type.html','Colours and typography',intro('Use these digital values from the retained SKAO Brand Book v2, March 2022.',tag='Brand essentials')+brand_essentials+block('Apply colour carefully',['Use navy for text and links on light backgrounds. Magenta works well as an accent; check each text/background pairing.','For print, use the Brand Book and the supplier’s agreed colour specifications rather than guessing CMYK or Pantone conversions.','Use labels, symbols or patterns as well as colour to communicate meaning.'])+nextstep('Need Noto Sans?','Use the official font source or your organisation’s approved installation route.','fonts.html','Find font guidance'))
 put('logo-guidance.html','Using the SKAO logo',intro('Use official artwork, preserve its proportions and give it space.', 'logos.html','Find logo files','Brand essentials')+block('Before placing the logo',['Choose a supplied variant suited to the background.','Leave at least half the logo’s height clear on all sides, following the retained Brand Book.','Do not stretch, recolour, redraw or add effects to the artwork.','For detailed sizing and specialist applications, use the Brand Book.'])+nextstep('Partner branding?','Check the applicable partner guidance before combining identities.','brand.html','Return to brand guidance'))
 put('brand-in-practice.html','Apply the brand',intro('Use the existing templates and artwork to keep your work recognisably SKAO.',tag='Practical application')+block('A quick self-check',['Logo: supplied artwork, correct variant, clear space and original proportions.','Type: Noto Sans, with Verdana as fallback.','Colour: the sourced palette and readable contrast.','Images: relevant to the message, with asset-specific credits and permissions.'])+nextstep('Start from existing material','Choose a template rather than rebuilding the layout.','resources.html','Find a resource'))
 for name,partner in [('co-branding-csiro.html','CSIRO'),('co-branding-sarao.html','SARAO')]:
  put(name,'Co-branding with '+partner,intro('Confirm the current '+partner+' and SKAO guidance for this particular use before preparing a combined layout.',tag='Partner identity')+nextstep('Need the approved arrangement?','Send the output, audience, partner and draft layout. The source page has no linked co-branding pack.',jira,'Ask for co-branding guidance ↗')+block('Bring to the review',['The current logo files supplied by each organisation.','The proposed placement, output size and background.','The relevant partner contact or approval route.'])+'<p class="quiet-note">A standard arrangement or minimum size is not assumed here. Use the confirmed guidance for the application.</p>')
 # Media routes stay in Canto; no speculative deep links or uploads.
 media_specs=[('media.html','Photos and video','Find media in Canto, then check each asset’s details before downloading.','Start with a subject, site or event; narrow by media type and date.'),('video.html','Video and animation','Find existing footage or animation before requesting a new production.','Search for the topic or event and filter for video.'),('hero-images.html','Hero images','Find a strong image for a cover, banner or presentation.','Search by subject and check the crop, resolution and use restrictions.'),('event-photos.html','Event photography','Find photos from a specific event.','Search by event name and date; check the rights and consent information for images of people.'),('telescope-images.html','Telescope imagery','Find images of SKA-Low, SKA-Mid and construction activity.','Search by telescope, location and date. Distinguish photography from artist impressions.'),('b-roll.html','B-roll footage','Find footage for an edit or presentation.','Search by subject and location; check duration, format, audio and usage restrictions.'),('recordings.html','Event recordings','Find a recorded talk, webinar or event session.','Search by event, speaker and date. Check permission for the intended audience and any excerpt.'),('animations.html','Explainer animations','Find an existing explanation of a topic or technology.','Search by subject and check whether the science and technical depiction remain current.')]
 for name,title,desc,tip in media_specs:
  put(name,title,intro(desc,canto,'Open the Canto library ↗','Media in Canto')+'<div class="media-handoff"><span aria-hidden="true">↗</span><div><h2>Search in the source library</h2><p>'+tip+'</p><p class="quiet-note">This opens the general staff library. A verified collection-specific link is not yet available here.</p></div></div>'+block('Before using an asset',['Read the credit, copyright and usage information on the asset.','Check that it suits your intended audience and use. Availability alone is not permission for every use.','Choose an appropriate download format; keep the credit with your working file.'])+nextstep('Can’t find or access the material?','Include your search terms, intended use and the link or error shown.','canto-access.html','Get help with Canto')+(nextstep('Need new video?','Bring the audience, message and source material.','video-request.html','Prepare a video brief') if name=='video.html' else ''))
 for name in ['canto-guide.html','canto-access.html']:
  put(name,'Using the Canto library',intro('Canto is the source library for media. The Hub provides guidance and routes to it.',canto,'Open the Canto library ↗','Find and use media')+block('Find, check, download',['Search for a subject, event or location, then narrow the results with available filters.','Open an asset and read its credits, use restrictions and available download formats.','Download the appropriate version and keep the source link with your work.'],True)+detail('I can’t access or download a file','<p>Send the library or asset link and the error message through '+link(jira,'the creative helpdesk')+'. Do not include passwords. Browsing and download permissions may differ.</p>')+detail('I want to upload material','<p>Use the authorised upload route provided for your material. '+link('contribute.html','See how to contribute')+'.</p>')+nextstep('Looking for presentation slides?','Presentation releases belong in the Hub.','presentations.html','Find presentation resources'))
 put('image-usage.html','Use and credit imagery',intro('Read the information on the individual asset before reusing it.',canto,'Check the asset in Canto ↗','Credits and permitted use')+block('Check these details',['Credit: copy the required wording from the asset record; do not guess a generic SKAO or partner credit.','Rights: check the intended use, audience, restrictions and any consent information.','Format: use a suitable download, not a screenshot or watermarked preview.','Meaning: retain context and identify artist impressions or visualisations appropriately.'])+nextstep('Missing or unclear information?','Share the asset link and your intended use before publishing.',jira,'Ask about the asset ↗'))
 put('working-with-us.html','Work with Creative Production',intro('Start with an existing resource. If you need new work or a review, bring a clear brief.','request.html','Prepare a request','How we work')+cards([('Use existing material','Templates, slides, logos and media.','resources.html','Find a resource'),('Scope creative work','Understand what to bring and what needs agreement.','creative-services.html','Check the scope'),('Plan the timing','Agree the use date, inputs and review stages.','timing.html','Plan the work')]))
 put('creative-services.html','What we can help with',intro('Creative Production helps shape and produce agreed creative materials. The brief determines the work and the capacity required.','request.html','Discuss the creative work','Scope and responsibilities')+block('Examples to discuss',['Design and layout for publications, presentations and graphics.','Video, animation and creative digital work.','Visual identity, templates and reusable resources.','Creative materials for events, print and displays.'])+'<div class="responsibility-split"><section><h2>Bring the content</h2><p>The requester supplies the purpose, audience, draft or source material and the appropriate content reviewer.</p></section><section><h2>Agree the production</h2><p>The team confirms the outputs, responsibilities, timing and any supplier requirements.</p></section></div>'+nextstep('Event logistics or editorial ownership?','Use the responsible team’s route. A creative brief does not transfer all project responsibilities to Creative Production.','events.html','See event responsibilities'))
 put('timing.html','Agree scope and timing',intro('Give the actual use date and explain what depends on it. Delivery timing is agreed after the brief and capacity are reviewed.','request.html','Send the brief','Planning the work')+block('What affects the schedule',['When usable content and source files will be ready.','The output, complexity and amount of adaptation required.','Who reviews the work and when they can respond.','Supplier production, delivery and other dependencies.'])+nextstep('An urgent request?','State the real deadline, its reason and what can be reduced. Urgency does not automatically create a delivery commitment.',jira,'Open the helpdesk ↗'))
 put('faq.html','Common questions',intro('Short answers to the most common Hub questions.',tag='Help and next steps')+detail('Where are templates and slides?','<p>Start with '+link('resources.html','Templates and assets')+'. The source pages show file availability. Presentation releases belong in the Hub.</p>')+detail('Where are photos and video?','<p>Use '+link(canto,'the Canto library ↗')+' and check each asset’s credit and permitted use.</p>')+detail('Can I adapt material myself?','<p>Follow the release’s usage notes and keep credits. Ask the relevant content owner about changes to facts or meaning; ask Creative Production about substantial design work.</p>')+detail('Who approves the work?','<p>Identify the appropriate content owner and final reviewer in the brief. The approval route depends on the work and should be confirmed rather than assumed.</p>')+detail('Can I get an urgent turnaround?','<p>Explain the use date and any flexibility. '+link('timing.html','Scope and timing need agreement')+'.</p>')+nextstep('Still stuck?','Include the relevant page or asset link.',jira,'Ask for help ↗'))
 put('self-service.html','Self-service guides',intro('Practical checks for work you can prepare using existing resources.',tag='Do it with confidence')+cards([('Prepare slides','Structure, sources and accessibility.','formatting-slides.html','Read the slide guide'),('Make a poster','Choose a layout and check the output.','making-a-poster.html','Read the poster guide'),('Prepare print files','Get the supplier specifications right.','print-preparation.html','Read the print guide')]))
 put('formatting-slides.html','Format a presentation',intro('Start with a suitable template and build the talk around your audience.','presentations.html','Find presentation resources','Self-service guide')+block('Build the story',['Give each slide a clear purpose and use readable, concise headings.','Use the supplied layouts and keep spacing, alignment and typography consistent.','Use imagery and charts to explain the message; retain their sources and credits.'])+block('Check before presenting',['Try the deck on the intended display and check that text and charts are readable from the audience’s position.','Check contrast, alternative text and reading order. Caption any video.','Check facts, dates and any adapted claims with the appropriate content owner.'])+nextstep('Need more than formatting?','Bring the draft and audience brief.','request.html','Ask for a review'))
 put('making-a-poster.html','Prepare a poster',intro('Confirm the organiser’s dimensions and output requirements before choosing a layout.','poster-templates.html','Check poster templates','Self-service guide')+block('Prepare the content',['Decide the main message, title, authors and the information the audience needs.','Use readable headings, a clear reading order and enough space around figures.','Keep credits and sources with images and charts.'])+block('Prepare the output',['Confirm print size, orientation and submission format with the organiser or supplier.','Check image resolution at the intended size and proof the exported file.','Confirm colour, bleed and delivery requirements with the supplier.'])+nextstep('Sending it to print?','Use the actual supplier requirements.','print-preparation.html','Check print preparation'))
 put('print-preparation.html','Prepare files for print',intro('Use the supplier’s specifications for the actual product. A single export recipe does not fit every print job.',tag='Before supplier handoff')+block('Confirm the specification',['Finished dimensions, trim, bleed and safe area.','Colour profile and any spot colours or special finishes.','Required PDF standard, image resolution and font handling.','Proof process, quantity, final artwork deadline and delivery details.'],True)+block('Check the exported file',['Review text, page order, dimensions and image quality.','Check fonts, colour and overprint settings as appropriate to the supplier’s workflow.','Get the required content and artwork approvals before production.'])+nextstep('Need production support?','Send the specification and draft artwork, with any unresolved questions.','request.html','Brief the print work'))
 for name,title,desc,items in [
 ('print.html','Plan print materials','Define what needs producing before asking for artwork or a quote.',['Output, dimensions, quantity and intended audience.','Existing artwork or draft content and image sources.','Delivery location, use date and supplier deadlines.','Budget, final reviewer and any finishing requirements.']),
 ('business-cards.html','Request business cards','Confirm the required contact details, quantity and delivery need.',['Name and job title, checked by the requester.','Business contact details for the card.','Quantity, language requirements and delivery location.','Required use date and the person who will approve the proof.']),
 ('merchandise.html','Plan merchandise','Start with the purpose and audience. Check existing stock before commissioning new items.',['Why the item is useful for the audience.','Available stock or an existing design that could be reused.','Quantity, budget, destination and use date.','Supplier requirements, material choices and the artwork reviewer.']),
 ('stands.html','Plan stand graphics','Check the existing kit and the venue’s specification before briefing new graphics.',['Available stand system and reusable graphics.','Venue dimensions, supplier artwork templates and display restrictions.','Audience, key messages and draft content.','Artwork reviewer, supplier deadline and event organiser contacts.']),
 ('video-request.html','Brief video or animation','Check existing footage first, then explain what a new piece needs to achieve.',['Audience, message and where the piece will be used.','Existing footage, draft script, images and source information.','Length or format constraints and accessibility needs.','Content reviewer, use date, budget and any filming dependencies.'])]:
  put(name,title,intro(desc,'request.html','Prepare the creative brief','Plan the work')+block('Include in the brief',items)+nextstep('Agree before producing','The team confirms scope and capacity; supplier timing, cost and approval are agreed for the actual job.','timing.html','How timing is agreed'))
 put('event-checklist.html','Event materials checklist',intro('Work back from the use date with the event organiser and supplier. Confirm the actual deadlines rather than relying on a generic countdown.',tag='Plan, review, hand over')+block('1. Define',['Audience, purpose, venue and outputs.','Existing resources or event kit that can be reused.','Content owner, organiser, supplier and final reviewer.'])+block('2. Prepare',['Supplier templates, dimensions, formats and artwork deadline.','Draft content, source images and required credits.','Budget and the applicable approvals.'])+block('3. Review and hand over',['Content and artwork proof reviewed by the agreed people.','Supplier-ready file checked against the specification.','Delivery and on-site arrangements confirmed by the event organiser.'])+nextstep('Ready to brief the work?','Include the dependencies and anything still missing.','request.html','Prepare a creative brief'))
 put('event-safety.html','Event safety responsibilities',intro('Use the event organiser and SKAO HSSE team for current safety requirements and approval.', 'https://jira.skatelescope.org/servicedesk/customer/portal/298','Open HSSE helpdesk ↗','Specialist guidance')+'<div class="responsibility-split"><section><h2>Event organiser and HSSE</h2><p>Confirm the applicable assessments, approvals and operational arrangements.</p></section><section><h2>Creative Production</h2><p>Include the relevant design and material requirements in the creative brief, and refer specialist questions to the responsible people.</p></section></div><p class="quiet-note">This Hub page is a route to the responsible team, not a safety procedure or an approval.</p>')
 put('print-suppliers.html','Work with print suppliers',intro('Confirm the supplier, specification, budget and approvals for the actual job.','request.html','Brief print support','Production handoff')+block('Before placing an order',['Check the applicable procurement process with the responsible team.','Agree who obtains the quote, approves expenditure and places the order.','Confirm who signs off content and the final artwork proof.','Agree production and delivery dates with the supplier.'])+'<p class="quiet-note">This page does not publish a supplier approval list or purchasing thresholds. Use the current procurement guidance.</p>')
 put('fonts.html','Fonts',intro('Use Noto Sans for the SKAO identity, with Verdana as the fallback.','https://fonts.google.com/noto/specimen/Noto+Sans','Open Noto Sans at Google Fonts ↗','Typography')+block('Use in your work',['Follow the template’s existing text styles where available.','Use your organisation’s approved installation route on a managed device.','Check the font in the exported or shared file, particularly when moving between applications.'])+nextstep('Can’t install the font?','Use the fallback and ask for help through your usual IT support route.','colours-and-type.html','Return to typography guidance'))
 put('accessibility.html','Accessibility checks',intro('Build accessibility into the document or presentation, then check the exported result.',tag='Make the work usable')+block('Content and structure',['Use clear headings, descriptive links and a logical reading order.','Give informative images alternative text that conveys their purpose. Decorative images should be ignored by assistive technology, for example with empty alt text in HTML.','Caption video and provide an appropriate text alternative for audio.'])+block('Appearance and interaction',['Use readable contrast: WCAG’s minimum is generally 4.5:1 for normal text and 3:1 for qualifying large text.','Do not rely on colour alone. Use labels, symbols or patterns too.','Check keyboard access and focus visibility for interactive content.'])+nextstep('Check the relevant standard','These checks are a starting point, not a claim that the work passes a full accessibility audit.','https://www.w3.org/WAI/WCAG22/quickref/','Open the W3C reference ↗'))
 put('firefly.html','Using AI image tools',intro('Use the current SKAO AI policy and approved tools before starting a task.',tag='Concept development')+block('Before using a tool',['Check whether the material is suitable for the approved service.','Use only data permitted by the current SKAO AI policy; do not upload confidential or personal material.','Verify factual accuracy, rights and suitability before using generated imagery in a deliverable.','Keep concept imagery clearly distinguished from photography or verified scientific representations.'])+nextstep('Need advice on a creative use?','Describe the purpose and proposed output without sending unsuitable source material.',jira,'Ask the creative team ↗')+'<p class="quiet-note">Tool availability, model versions and credit allocations are not confirmed by this page. Check the current approved service and account.</p>')
 put('updates.html','Hub updates',intro('Use the resource pages for current files and availability. Older announcements are not evidence that a release is ready.',tag='What has changed')+nextstep('Looking for the latest resource?','Open its source page and check the file and review information.','resources.html','Browse resources')+detail('Older announcements','<p>The existing announcements need review before they can be used as a current release log. '+link('archive.html','Open archive guidance')+'.</p>'))
 put('archive.html','Updates archive',intro('No verified release history is presented in this review build.',tag='Historical reference')+nextstep('Need a previous version?','Include the resource name and the version or date you need.',jira,'Ask for an earlier release ↗'))
 assert set(META).issubset(pages), 'Every observed interior route must have a reviewed page'
 return pages, META
