"""Task-led layouts shared by preview and theme. No asset availability is invented."""
def revise(pages, jira, canto, live):
 def link(url,text,cls=''):return f'<a class="{cls}" href="{url}">{text}</a>'
 def visual(kind):
  return {'slides':'<span class="mini-slide"><i>SKA Observatory</i><b>A shared story.</b><em></em></span><span class="slide-back"></span>', 'document':'<span class="mini-document"><b>SKAO</b><i></i><i></i><i></i><i></i></span>', 'brand':'<span class="mini-brand"><b>Aa</b><i></i><em></em></span>', 'media':'<svg viewBox="0 0 240 140" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="2"><path d="M30 33Q92 124 154 33Z M92 79V124 M63 125H121 M92 79L108 22 M104 26L133 42"/><circle cx="176" cy="30" r="5"/><path d="M183 30H219 M176 37V60 M152 99H220 M172 89V112"/></g></svg>'}[kind]
 def tile(kind,kicker,title,desc,href,cta,extra=''):
  return f'<a class="library-tile {"identity" if kind == "brand" else kind} {extra}" href="{href}"><div class="resource-art" aria-hidden="true">{visual(kind)}</div><div class="tile-copy"><span class="eyebrow">{kicker}</span><h3>{title}</h3><p>{desc}</p><span class="tile-cta">{cta} <span aria-hidden="true">→</span></span></div></a>'
 home='<div class="home-journey"><section class="welcome-band journey-band"><div class="welcome-copy"><p class="eyebrow">Your creative toolkit</p><h1>Good work starts here.</h1><p class="lead">Find a template, prepare a presentation or get creative support.</p><div class="actions"><a class="button" href="#library">Find a resource →</a></div></div><a class="presentation-feature" href="presentations.html"><div class="feature-art" aria-hidden="true"><span>SKA OBSERVATORY</span><strong>A shared story.<br>Your next talk.</strong></div><div class="feature-copy"><p class="eyebrow">Presenting the Observatory</p><h2>Start with the slide library</h2><p>Find templates, reusable slides and the right checks before you present.</p><span class="feature-link">Explore presentation resources →</span></div></a></section><section id="library" class="toolkit-band journey-band"><div class="band-heading"><div><p class="eyebrow">01 / Find and reuse</p><h2>What do you need?</h2></div><a href="resources.html" class="text-link">All templates and assets →</a></div><div class="quick-library">'
 for kind,title,desc,url in [('slides','Presentation slides','Templates and reusable decks','presentations.html'),('document','Document templates','Reports, letters and memos',live+'document-templates-381891700.html'),('brand','Logos and branding','Artwork and identity guidance','brand.html'),('media','Photos and video','Browse the Canto library ↗',canto)]:
  home+='<a class="quick-resource '+('identity' if kind=='brand' else kind)+'" href="'+url+'"><div class="resource-art" aria-hidden="true">'+visual(kind)+'</div><div class="quick-copy"><h3>'+title+'</h3><p>'+desc+'</p><span aria-hidden="true">↗</span></div></a>'
 home+='</div></section><section class="help-band journey-band"><div><p class="eyebrow">02 / Work with us</p><h2>Need a hand?</h2><p>For new creative work or a review, tell us what you need.<br class="desktop-break"> We’ll agree the scope and timing with you.</p></div><div class="help-actions"><a class="button" href="request.html">Start a creative request <span aria-hidden="true">→</span></a><a href="'+jira+'">Already have a brief? Open the helpdesk ↗</a></div></section></div>'
 resources='''<p class="lead">Choose the material you need. Each route opens its source page or library, where you can check the available files and usage notes.</p><details class="catalogue-filters"><summary>Filter categories</summary><div class="filters"><label>Filter these categories<input id="resourceFilter" type="search" placeholder="Try slides, logos or reports"></label><label>Type<select id="resourceType"><option value="all">All types</option><option value="presentation">Presentations</option><option value="document">Documents</option><option value="brand">Brand</option><option value="media">Media</option></select></label><button id="clearFilters" type="button" class="button secondary">Clear filters</button></div><p id="filterStatus" class="status" role="status">4 categories shown.</p></details><div class="catalogue">'''
 data=[('presentation','slides','Presentation templates and slides','For talks, briefings and reusable presentation content.','Hub · source pages','presentations.html','Browse presentation resources'),('document','document','Document templates','For reports, letterheads and memos.','Hub · source pages',live+'document-templates-381891700.html','Open document templates'),('brand','brand','Logos and brand guidance','For logo artwork, colours, typography and co-branding.','Hub · guidance and files','brand.html','Open brand guidance'),('media','media','Photography and video','Find media, then check credits and usage information.','Canto · separate library',canto,'Open Canto ↗')]
 for typ,kind,title,desc,loc,url,cta in data:
  resources+=f'<article class="catalogue-item" data-resource data-type="{typ}"><div class="catalogue-art {kind}" aria-hidden="true">{visual(kind)}</div><div><span class="eyebrow">{loc}</span><h2>{title}</h2><p>{desc}</p>{link(url,cta,"text-link")}</div></article>'
 resources+='''</div><aside class="missing-resource"><h2>Can’t find what you need?</h2><p>Clear the filters to see all categories, or tell the team which resource is missing.</p><a href="request.html">Ask for help finding a resource →</a></aside>'''
 request=pages['request.html'][1]
 request=request.replace('<h2>Prepare a short brief</h2>', '<div class="process-strip" aria-label="Request process"><span><b>1</b> Prepare here</span><span><b>2</b> Copy and submit in Jira</span><span><b>3</b> Agree scope</span></div><h2>Prepare a short brief</h2>')
 request=request.replace('<form id="briefForm" hidden>','<p class="form-note">Fields marked * are required. Your draft stays on this page and is lost if you leave or reload.</p><form id="briefForm" hidden>')
 request=request.replace('Go straight to the creative helpdesk','Already have a brief? Open the helpdesk ↗')
 contribute='''<p class="lead">Help colleagues reuse good work. Choose what you’re sharing to see where it goes and what to include.</p><div class="submission-note"><strong>Submission starts a review.</strong> It does not publish your file or approve it for reuse.</div><div class="submission-routes"><section><span class="route-label">Presentation → Creative helpdesk</span><h2>Share a slide deck</h2><p>Attach the editable deck or an approved source link. Include the title, audience, event/date, content owner and reuse restrictions.</p>'''+link(jira,'Send a deck for review ↗','button')+'''<small>Accepted releases belong in the Hub.</small></section><section><span class="route-label">Photos or video → Canto</span><h2>Contribute media</h2><p>If you have an authorised Canto upload route, use it and include creator credit, date, location and usage/consent information.</p>'''+link(jira,'Ask for media upload access ↗','button secondary')+link(canto,'Browse existing media in Canto ↗','text-link')+'''<small>The library link is for browsing. It is not an upload form.</small></section></div><div class="correction-row"><div><h2>Something missing or incorrect?</h2><p>Send the page link, the change needed and its source.</p></div>'''+link(jira,'Send a correction ↗','text-link')+'''</div><h2>After you submit</h2><p>The responsible owner checks content, suitability and rights before release. Keep working files at their existing source and share a link when another attachment would create a competing version.</p>'''
 presentations=pages['presentations.html'][1]
 # Give the three starting points distinct, observed source destinations.
 old=[('For a new talk with your own content','Standard+SKAO+Template'),('Check the library for the latest released deck','About+SKAO+Master+Deck'),('Check audience, source, review date and permitted reuse','Science+Case+Presentations')]
 for desc,slug in old:
  marker=f'<small>{desc}</small>'
  at=presentations.index(marker); start=presentations.rfind('href="',0,at)+6; end=presentations.index('"',start)
  presentations=presentations[:start]+'https://confluence.skatelescope.org/display/CRH/'+slug+presentations[end:]
 brand=pages['brand.html'][1].replace(live+'brand-guidelines-381891606.html',live+'logos-icons-381891715.html').replace('Open current brand guidance','Open logo artwork and files')
 presentations=presentations.replace('<h2>Before you present</h2>', '<aside class="source-check"><span class="eyebrow">Check the source before reuse</span><h2>How current is this material?</h2><p>Look for the review date, content owner, version and reuse notes on the source page. Keep dates with facts and figures. A recent page edit alone does not mean its content has been reviewed.</p><p>If a date or source is missing, check with the content owner before presenting figures as current.</p></aside><h2>Before you present</h2>')
 presentations=presentations.replace('<h2>When to ask for a review</h2>', '<div class="reuse-decision"><h2>Reuse, adapt or ask?</h2><dl><dt>Using a released template or unchanged slides</dt><dd>Follow the source’s usage notes and keep credits. Start from the existing material.</dd><dt>Changing facts, claims or meaning</dt><dd>Ask the relevant content or science owner to review those changes.</dd><dt>Needing new design or substantial adaptation</dt><dd><a href="request.html">Prepare a creative brief</a> with your draft or source material.</dd></dl></div><h2>When to ask for a review</h2>')
 # The release schema belongs in the editorial handoff, not as implementation commentary for employees.
 at=presentations.find('<aside class="callout"><h2>Library release pattern</h2>')
 if at>=0: presentations=presentations[:at]
 pages['presentations.html']=('Prepare a presentation',presentations)
 pages['brand.html']=('Brand guidance',brand)
 pages.update({'index.html':('Creative Hub',home),'resources.html':('Templates and assets',resources),'request.html':('Request creative help',request),'contribute.html':('Share material',contribute)})
 return pages
